app/models/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, PasswordField, BooleanField, TextAreaField
# from app.utils.forms import MultiCheckboxField


class BookForm(FlaskForm):
    query = TextAreaField('Query')

app/utils/forms.py
# from flask_wtf import FlaskForm
#
# from wtforms import SubmitField, validators, SelectMultipleField
# from wtforms.widgets import CheckboxInput, ListWidget
#
#
# class MultiCheckboxField(SelectMultipleField):
#     """
#     A multiple-select, except displays a list of checkboxes.
#
#     Iterating the field will produce subfields, allowing custom rendering of
#     the enclosed checkbox fields.
#     """
#     widget = ListWidget(prefix_label=False)
#     option_widget = CheckboxInput()
#
# class ConfirmationForm(FlaskForm):
#     submit = SubmitField('Confirm')

app/__init__.py
import os
from datetime import datetime

from beaker.cache import CacheManager
from beaker.middleware import SessionMiddleware
from beaker.util import parse_cache_config_options
from celery import Celery
from flask import Flask, render_template
from flask.sessions import SessionInterface
# from flask_migrate import Migrate

# Instantiate Flask extensions
# migrate = Migrate()


def get_config():
    # Instantiate Flask
    app = Flask(__name__)

    # Load App Config settings
    # Load common settings from 'app/settings.py' file
    app.config.from_object('app.settings')
    # Load local settings from environmental variable
    if 'APPLICATION_SETTINGS' in os.environ:
        app.config.from_envvar(os.environ['APPLICATION_SETTINGS'])
    # Load extra config settings from the AWS Secrets Manager
    if 'AWS_SECRETS_MANAGER_CONFIG' in os.environ:
        secret_config = get_secrets(os.environ['AWS_SECRETS_MANAGER_CONFIG'])
        app.config.update(secret_config)
    elif 'AWS_SECRETS_MANAGER_CONFIG' in app.config:
        secret_config = get_secrets(app.config['AWS_SECRETS_MANAGER_CONFIG'])
        app.config.update(secret_config)
    # Load extra config settings from environment- note that the config key must exist in app.config to get picked up
    for setting in app.config:
        if setting in os.environ:
            if os.environ[setting].lower() == 'true':
                app.config[setting] = True
            elif os.environ[setting].lower() == 'false':
                app.config[setting] = False
            else:
                app.config[setting] = os.environ[setting]
    # Apply any config transformations here.
    if app.config.get('USER_LDAP', False):
        app.config['USER_ENABLE_USERNAME'] = True
    return app.config


# We need the base configuration to setup services before the app is created.
base_config = get_config()

# Initiate Services
celery = Celery(__name__, broker=base_config['CELERY_BROKER'])
cache = None # Initiate below, but define here for scope reasons.


def create_app(extra_config_settings={}):
    """Create a Flask applicaction.
    """
    # Instantiate Flask
    app = Flask(__name__)

    # Load extra config settings from 'extra_config_settings' param
    base_config = get_config()
    app.config.update(base_config)
    # Load extra config settings from 'extra_config_settings' param
    app.config.update(extra_config_settings)

    # Setup Session Manager
    init_session_manager(app)

    # Setup Celery
    init_celery_service(app)

    # Add HTTP Error pages
    init_error_handlers(app)

    # Register blueprints
    from app.extensions.jinja import jinja_extensions_blueprint
    app.register_blueprint(jinja_extensions_blueprint)
    app.jinja_env.globals.update(now=datetime.utcnow)

    from app.views.main_page import main_blueprint
    app.register_blueprint(main_blueprint)

    # Setup an error-logger to send emails to app.config.ADMINS
    if app.config.get('EMAIL_ERRORS', False):
        init_email_error_handler(app)

    return app


def init_cache_manager(app):
    cache_opts = {'cache.expire': app.config.get('CACHE_EXPIRE', 3600)}

    if 'CACHE_TYPE' not in app.config or not app.config['CACHE_TYPE']:
        app.config['CACHE_TYPE'] = 'file'

    if app.config['CACHE_TYPE'] == 'file':
        if 'CACHE_ROOT' not in app.config or not app.config['CACHE_ROOT']:
            app.config['CACHE_ROOT'] = '/tmp/%s' % __name__

    cache_opts['cache.type'] = app.config['CACHE_TYPE']

    if 'CACHE_ROOT' in app.config and app.config['CACHE_ROOT']:
        cache_opts['cache.data_dir'] = app.config['CACHE_ROOT'] + '/data'
        cache_opts['cache.lock_dir'] = app.config['CACHE_ROOT'] + '/lock'

    if 'CACHE_URL' in app.config and app.config['CACHE_URL']:
        cache_opts['cache.url'] = app.config['CACHE_URL']


    cache = CacheManager(**parse_cache_config_options(cache_opts))


def init_session_manager(app):
    session_opts = {'cache.expire': 3600}

    if 'CACHE_TYPE' not in app.config or not app.config['CACHE_TYPE']:
        app.config['CACHE_TYPE'] = 'file'

    if app.config['CACHE_TYPE'] == 'file':
        if 'CACHE_ROOT' not in app.config or not app.config['CACHE_ROOT']:
            app.config['CACHE_ROOT'] = '/tmp/%s' % __name__

    session_opts['session.type'] = app.config['CACHE_TYPE']

    if 'CACHE_ROOT' in app.config and app.config['CACHE_ROOT']:
        session_opts['session.data_dir'] = app.config['CACHE_ROOT'] + '/session'

    if 'CACHE_URL' in app.config and app.config['CACHE_URL']:
        session_opts['session.url'] = app.config['CACHE_URL']

    session_opts['session.auto'] = app.config.get('SESSION_AUTO', True)
    session_opts['session.cookie_expires'] = app.config.get('SESSION_COOKIE_EXPIRES', 86400)
    session_opts['session.secret'] = app.secret_key

    class BeakerSessionInterface(SessionInterface):
        def open_session(self, app, request):
            session = request.environ['beaker.session']
            return session

        def save_session(self, app, session, response):
            session.save()

    app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
    app.session_interface = BeakerSessionInterface()


def init_celery_service(app):
    celery.conf.update(app.config)


def init_error_handlers(app):

    def show_error(status, message='An unknown error has occured.'):
        return render_template('pages/errors.html', error_code=status, message=message), status

    @app.errorhandler(401)
    def error_unauthorized(e):
        return show_error(401, 'Unauthorized')

    @app.errorhandler(403)
    def error_forbidden(e):
        return show_error(403, 'Forbidden')

    @app.errorhandler(404)
    def error_pagenotfound(e):
        return show_error(404, 'Page not found.')

    @app.errorhandler(500)
    def error_servererror(e):
        return show_error(500, 'An unknown error has occurred on the server.')

app/views/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

app/views/main_page.py
# Copyright 2017 Twin Tech Labs. All rights reserved

from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask import Blueprint, render_template

from book_collector import BookCollector
from wordnet import bag_words, detect_language, rank_categories, detect_genre
from ..models.forms import BookForm
from requests.exceptions import HTTPError

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')


@main_blueprint.route('/', methods=['GET', 'POST'])
def main_page():
    form = BookForm(request.form)

    if request.method == 'POST':
        try:
            scores = BookCollector(form.query.data).collect()
            for score in scores:
                print(score.book[1])
                print(score.scores, "\n")
            return render_template('pages/book_recommender.html', query=form.query.data,
                                   result=scores[:10])
        except HTTPError as e:
            print(e)
            error = str(e)
            error_list = error.split(" ")
            return render_template('pages/errors.html', error_code=error_list[0], message=e, url=error_list[-1])

        # return redirect(url_for('main.example_page'))

    return render_template('pages/book_recommender.html', query="Red turtle swims fast", result=None)


@main_blueprint.route('/example')
def example_page():
    return render_template('pages/example.html')

wordnet/__init__.py
import nltk

from wordnet.category import rank_categories
from wordnet.detect_hyponym import detect_language, detect_genre
from wordnet.bag_of_words import bag_words

nltk.download('wordnet')
nltk.download('punkt')
nltk.download('stopwords')

app/templates/common/dark_base.html
{% extends "dark_layout.html" %}

app/templates/common/form_macros.html
{% macro render_field(field, label=None, label_visible=true, right_url=None, right_label=None) -%}
    <div class="form-group{% if field.errors %} has-error {% endif %}{{ kwargs.pop('class_', '') }}">
        {%- if field.type != 'HiddenField' and label_visible -%}
            {%- if not label -%}{% set label=field.label.text %}{%- endif %}
            <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
        {%- endif %}
            {{ field(class_='form-control', **kwargs) }}
        {%- if field.errors -%}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {%- endif %}
    </div>
{%- endmacro %}

{% macro render_multicheckbox_field(field, label=None, label_visible=true) -%}
    <div class="form-group{% if field.errors %} has-error {% endif %}{{ kwargs.pop('class_', '') }}">
      {%- if field.type != 'HiddenField' and label_visible -%}
          {%- if not label -%}{% set label=field.label.text %}{%- endif %}
          <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
      {%- endif %}
      {% for value, label, checked in field.iter_choices() %}
          <div class="checkbox">
              <label>
                <input type="checkbox" name="{{ field.id }}" id="{{ field.id }}-{{ loop.index }}" value="{{ value }}"{% if checked %} checked{% endif %}>
                {{ label }}
              </label>
          </div>
      {% endfor %}
    </div>
{%- endmacro %}


{% macro render_checkbox_field(field, label=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ label }}
        </label>
    </div>
{%- endmacro %}

{% macro render_radio_field(field, label=None, label_visible=true) -%}

    <div class="form-group{% if field.errors %} has-error {% endif %}{{ kwargs.pop('class_', '') }}">

      {%- if field.type != 'HiddenField' and label_visible -%}
          {%- if not label -%}{% set label=field.label.text %}{%- endif %}
          <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
      {%- endif %}

      {% for value, label, checked in field.iter_choices() %}
          <div class="radio">
              <label>
                  <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}"{% if checked %} checked{% endif %}>
                  {{ label }}
              </label>
          </div>
      {% endfor %}

  </div>
{%- endmacro %}

{% macro render_submit_field(field, label=None, tabindex=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    {#<button type="submit" class="form-control btn btn-default btn-primary">{{label}}</button>#}
    <input type="submit" value="{{label}}"
           {% if tabindex %}tabindex="{{ tabindex }}"{% endif %}
           >
{%- endmacro %}

app/templates/common/page_base.html
{% extends "layout.html" %}

app/templates/dark_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title_tag %}
        <title>{{ config['APP_NAME'] }}{% block title %}{% endblock %}</title>
        {% endblock %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <!-- stylesheets and javascript -->
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" integrity="sha256-q5+FXlQok94jx7fkiX65EGbJ27/qobH6c6gmhngztLE=" crossorigin="anonymous" />

        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.js" integrity="sha256-nB5IzxtznpdsVh/iELG3YdRF71rcxuh4tItH2jWfg/w=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/css/perfect-scrollbar.css" integrity="sha256-e2UIyejgTejr/sXeLOHEMDvEagonkoPv9+JIwckAqRs=" crossorigin="anonymous" />

        <link href="{{ url_for('static', filename='/coreui/dist/css/coreui.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='/coreui/dist/js/coreui.min.js') }}"></script>

    </head>
    <body>
        {% block body %}
        <div class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
          <header class="app-header navbar">
            <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.main_page') }}">
              {{ config['APP_NAME'] }}
            </a>
          </header>
          <div class="app-body">
            <div class="sidebar">
              <nav class="sidebar-nav">
                <ul class="nav">

                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle" href="#">
                      <i class="nav-icon icon-bell"></i> My Account</a>
                  </li>

                </ul>
              </nav>
            </div>

          {% block pre_content %}{% endblock %}

          <main class="main">
          {# One-time system messages called Flash messages #}
          {% block flash_messages %}
              {%- with messages = get_flashed_messages(with_categories=true) -%}
                  {% if messages %}
                      {% for category, message in messages %}
                          {% if category=='error' %}
                              {% set category='danger' %}
                          {% endif %}
                          <div style="margin-bottom: -2px;" role="alert" class="alert alert-{{category}} alert-dismissible fade show">{{ message|safe }}</div>
                      {% endfor %}
                  {% endif %}
              {%- endwith %}
          {% endblock %}

          <!-- Breadcrumb-->
          <ol class="breadcrumb">
            {% block breadcrumb %}
            {% endblock %}
          </ol>

          <div class="container-fluid">
            <div class="animated fadeIn">
              {% block content %}{% endblock %}
            </div>
          </div>

          </main>
          {% block post_content %}{% endblock %}

        {% endblock %}
        </div>
        <footer class="app-footer">
          <div>{{ config['APP_NAME'] }} &copy; {{ now().year }} {{ config['APP_OWNER_NAME'] }}</div>
        </footer>
      </div>
        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
                {% block onstart_javascript %}{% endblock %}
            })();
            {% block page_load_javascript %}{% endblock %}
        </script>
    </body>
</html>

app/templates/pages/book_recommender.html
{% extends "common/dark_base.html" %}

{% block breadcrumb %}
{% endblock %}
{% block content %}
{% from "common/form_macros.html" import render_field, render_submit_field %}
<div class="card ">
  <form action="" method="POST" class="form" role="form">
    <div class="card-header ">
      <strong>User Profile</strong>
    </div>
    <div class="card-body ">
      <div class="form-group ">
        <label for="nf-email ">Query</label>
        <textarea class="form-control" id="query" name="query" placeholder="Enter query">{{query}}</textarea>
      </div>
    </div>
    <div class="card-footer ">
      <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
{#      <button type="reset " class="btn btn-sm btn-danger "><i class="fa fa-ban "></i> Reset</button>#}
    </div>
    {% if result %}
    <h1>Recommendations</h1>
    <div class="results ">
     <table style="border: 2px solid black; width:100%">
      <tr style="border: 2px solid black;">
        <th style="border: 2px solid black;">Book title</th>
        <th style="border: 2px solid black;">Description</th>
        <th style="border: 2px solid black;">Similarity</th>
      </tr>
      {% for row in result %}
        <tr style="border: 2px solid black;">
          <td style="border: 2px solid black;">{{row.book[1]}}</td>
          <td style="border: 2px solid black;">{{row.book[2]}}</td>
          <td style="border: 2px solid black;">{{row.final_score}}</td>
        </tr>
      {% endfor %}
     </table>
    </div>
    {% endif %}
  </form>
</div>
{% endblock %}

app/templates/pages/errors.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block title %} - {{ error_code }} Error{% endblock %}
{% block content %}
{% from "common/form_macros.html" import render_field %}
<div class="card ">
  <form action="" method="POST" class="form" role="form">
    <div class="card-header ">
      <strong>A {{ error_code }} Error Occurred</strong>
    </div>
    <div class="card-body ">
      <a href="{{ url }}" target="_blank">Error website</a>
      <br>
      {{ message }}
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/member_base.html
{% extends "common/dark_base.html" %}

{% block content %}
<div class="row">
  <h1>Hello, world!</h1>
</div>
{% endblock %}

app/templates/pages/user_profile_page.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
{% block breadcrumb %}
{% endblock %}
{% block content %}
{% from "common/form_macros.html" import render_field, render_submit_field %}
<div class="card ">
  <form action="" method="POST" class="form" role="form">
    <div class="card-header ">
      <strong>User Profile</strong>
    </div>
    <div class="card-body ">
          {{ form.hidden_tag() }}
          <div class="form-group ">
            <label for="nf-email ">First name</label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name" value="{{current_user.first_name}}">
          </div>
          <div class="form-group ">
            <label for="nf-password ">Last name</label>
            <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name" value="{{current_user.last_name}}">
          </div>
    </div>
    <div class="card-footer ">
      <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
      <button type="reset " class="btn btn-sm btn-danger "><i class="fa fa-ban "></i> Reset</button>
    </div>
  </form>
</div>
{% endblock %}